wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.10.25
      8:
      - 5
batch_size:
  desc: null
  value: 32
epsilon:
  desc: null
  value: 0.7
epsilon_dec:
  desc: null
  value: 1.0e-05
epsilon_min:
  desc: null
  value: 0.0
fc_layer_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.001
max_steps:
  desc: null
  value: 300000
mem_size:
  desc: null
  value: 50000
optimizer:
  desc: null
  value: adam
replace:
  desc: null
  value: 1000
