wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.10.25
      8:
      - 5
method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    goal: maximize
    name: reward
parameters:
  desc: null
  value:
    batch_size:
      values:
      - 16
    epochs:
      values:
      - 1000
    fc_layer_size:
      values:
      - 32
    gamma:
      values:
      - 0.99
    learning_rate:
      values:
      - 0.01
