wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.10.25
      8:
      - 5
batch_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 3000
fc_layer_size:
  desc: null
  value: 32
gamma:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: adam
