wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.8.5
      5: 0.10.25
      8:
      - 5
batch_size:
  desc: null
  value: 32
fc_layer_size:
  desc: null
  value: 64
gamma:
  desc: null
  value: 0.6
learning_rate:
  desc: null
  value: 0.01
max_steps:
  desc: null
  value: 200000
optimizer:
  desc: null
  value: adam
